---
# {{ ansible_managed }}
version: '3.5'

networks:
    proxy:
      external: true
      name: net_proxy # the external name

services:
  proxy:
    image:  jwilder/nginx-proxy
    ports:
      - "100:80"
    deploy:
      mode: global
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy
