---
- name: Install Docker daemon
  become: true
  yum:
    name: "{{ item }}"
    state: present
    disable_gpg_check: yes
  with_items:
    - "{{ docker_rhel_package_name }}"
    - device-mapper-persistent-data
    - lvm2

- name: Change semaphore limits
  become: true
  sysctl:
    name: kernel.sem
    value: "32000  1024000000  500  32000"
